// AGSPE Mock Data - Adani Group Strategic Prediction Engine

export interface Prediction {
  id: string;
  likely_action: string;
  category: string;
  timeline_start: string;
  timeline_end: string;
  confidence_score: number;
  supporting_evidence: string[];
  risk_factors: string[];
  financial_signal: number;
  political_alignment: number;
  pattern_match: string;
  validation_score: number;
}

export interface Financial {
  id: string;
  company_name: string;
  ticker: string;
  market_cap_inr: number;
  market_cap_usd: number;
  debt_to_equity: number;
  stock_price: number;
  stock_price_usd: number;
  volume: number;
  sector: string;
  change_percent: number;
  pe_ratio: number;
}

export interface NewsArticle {
  id: string;
  title: string;
  source: string;
  source_tier: number;
  published_at: string;
  content_snippet: string;
  validation_score: number;
  bias_risk_level: "Low" | "Medium" | "High";
  tag: "Verified" | "Unverified" | "Requires Verification" | "Pro-Group";
  related_companies: string[];
  keywords: string[];
}

export interface LobbyingRecord {
  id: string;
  entity: string;
  country: string;
  amount_usd: number;
  quarter: string;
  year: number;
  law_firm: string;
  disclosure_type: string;
  description: string;
}

export interface Acquisition {
  id: string;
  company_acquired: string;
  acquirer: string;
  year: number;
  valuation_inr: number;
  valuation_usd: number;
  status: "Active" | "Integrated" | "Demerged" | "Pending Litigation";
  sector: string;
}

export const predictions: Prediction[] = [
  {
    id: "pred-001",
    likely_action: "New Airport Concession Win (Phase 3 Privatization)",
    category: "Infrastructure",
    timeline_start: "Q3 2026",
    timeline_end: "Q1 2027",
    confidence_score: 82.5,
    supporting_evidence: [
      "Government announced Phase 3 airport privatization",
      "Adani already operates 7 airports",
      "Union Budget 2026-27 allocated record infrastructure spending",
    ],
    risk_factors: [
      "Regulatory scrutiny risk",
      "Competitive bidding from Tatas and GMR",
    ],
    financial_signal: 0.72,
    political_alignment: 0.85,
    pattern_match: "Port & Infrastructure Play",
    validation_score: 0.82,
  },
  {
    id: "pred-002",
    likely_action: "Green Hydrogen JV with International Partner",
    category: "Green Energy",
    timeline_start: "Q4 2026",
    timeline_end: "Q2 2027",
    confidence_score: 76.3,
    supporting_evidence: [
      "National Green Hydrogen Mission with INR 19,744 Cr allocation",
      "TotalEnergies partnership precedent",
    ],
    risk_factors: ["High capex requirement", "Technology maturation risk"],
    financial_signal: 0.68,
    political_alignment: 0.78,
    pattern_match: "Green Energy Expansion",
    validation_score: 0.76,
  },
  {
    id: "pred-003",
    likely_action: "Distressed Cement Asset Acquisition (NCLT)",
    category: "M&A",
    timeline_start: "Q1 2027",
    timeline_end: "Q3 2027",
    confidence_score: 71.8,
    supporting_evidence: [
      "Ambuja/ACC consolidation nearing completion",
      "NCLT pipeline active",
    ],
    risk_factors: ["Cyclicality risk", "Regulatory approval delays"],
    financial_signal: 0.65,
    political_alignment: 0.7,
    pattern_match: "Distressed Asset Acquisition",
    validation_score: 0.72,
  },
  {
    id: "pred-004",
    likely_action: "Data Center Capacity Expansion to 1 GW",
    category: "Digital Infrastructure",
    timeline_start: "Q2 2026",
    timeline_end: "Q4 2026",
    confidence_score: 68.4,
    supporting_evidence: [
      "AI demand surge",
      "Adani Data Networks license",
    ],
    risk_factors: [
      "High capital intensity",
      "Competition from Reliance Jio",
    ],
    financial_signal: 0.6,
    political_alignment: 0.65,
    pattern_match: "Digital Expansion",
    validation_score: 0.68,
  },
  {
    id: "pred-005",
    likely_action: "Defense Manufacturing Contract (Make in India)",
    category: "Defense",
    timeline_start: "Q3 2026",
    timeline_end: "Q1 2027",
    confidence_score: 62.1,
    supporting_evidence: [
      "Make in India defense policy",
      "UAV contract precedent",
    ],
    risk_factors: ["Limited track record", "Strong competitors"],
    financial_signal: 0.55,
    political_alignment: 0.72,
    pattern_match: "Policy Correlation - Defense",
    validation_score: 0.62,
  },
  {
    id: "pred-006",
    likely_action: "Port Capacity Expansion at Mundra & Krishnapatnam",
    category: "Infrastructure",
    timeline_start: "Q4 2026",
    timeline_end: "Q2 2027",
    confidence_score: 58.9,
    supporting_evidence: [
      "Sagarmala Phase 3 funding",
      "12% YoY container growth",
    ],
    risk_factors: [
      "Environmental clearance delays",
      "Competition from JNPT",
    ],
    financial_signal: 0.7,
    political_alignment: 0.6,
    pattern_match: "Port & Infrastructure Play",
    validation_score: 0.59,
  },
  {
    id: "pred-007",
    likely_action: "Solar Manufacturing Unit under PLI Scheme",
    category: "Green Energy",
    timeline_start: "Q1 2027",
    timeline_end: "Q3 2027",
    confidence_score: 55.2,
    supporting_evidence: ["PLI scheme active", "280 GW solar target"],
    risk_factors: ["PLI disbursement delays", "Chinese competition"],
    financial_signal: 0.62,
    political_alignment: 0.58,
    pattern_match: "Green Energy Expansion",
    validation_score: 0.55,
  },
];

export const financials: Financial[] = [
  {
    id: "fin-001",
    company_name: "Adani Enterprises",
    ticker: "ADANIENT",
    market_cap_inr: 2850000,
    market_cap_usd: 34132,
    debt_to_equity: 1.21,
    stock_price: 2945.5,
    stock_price_usd: 35.28,
    volume: 8540000,
    sector: "Conglomerate",
    change_percent: 1.24,
    pe_ratio: 95.6,
  },
  {
    id: "fin-002",
    company_name: "Adani Ports & SEZ",
    ticker: "ADANIPORTS",
    market_cap_inr: 3150000,
    market_cap_usd: 37725,
    debt_to_equity: 0.89,
    stock_price: 1524.75,
    stock_price_usd: 18.26,
    volume: 6230000,
    sector: "Ports & Logistics",
    change_percent: 0.87,
    pe_ratio: 32.4,
  },
  {
    id: "fin-003",
    company_name: "Adani Green Energy",
    ticker: "ADANIGREEN",
    market_cap_inr: 2250000,
    market_cap_usd: 26946,
    debt_to_equity: 2.15,
    stock_price: 1842.3,
    stock_price_usd: 22.06,
    volume: 4520000,
    sector: "Renewable Energy",
    change_percent: -0.45,
    pe_ratio: 78.2,
  },
  {
    id: "fin-004",
    company_name: "Adani Total Gas",
    ticker: "ATGL",
    market_cap_inr: 2680000,
    market_cap_usd: 32096,
    debt_to_equity: 0.48,
    stock_price: 895.6,
    stock_price_usd: 10.73,
    volume: 3210000,
    sector: "City Gas Distribution",
    change_percent: 0.32,
    pe_ratio: 112.5,
  },
  {
    id: "fin-005",
    company_name: "Adani Power",
    ticker: "ADANIPOWER",
    market_cap_inr: 1850000,
    market_cap_usd: 22156,
    debt_to_equity: 1.82,
    stock_price: 624.85,
    stock_price_usd: 7.48,
    volume: 12100000,
    sector: "Power Generation",
    change_percent: 2.15,
    pe_ratio: 18.6,
  },
  {
    id: "fin-006",
    company_name: "Adani Wilmar",
    ticker: "AWL",
    market_cap_inr: 580000,
    market_cap_usd: 6946,
    debt_to_equity: 0.35,
    stock_price: 425.3,
    stock_price_usd: 5.09,
    volume: 2890000,
    sector: "FMCG",
    change_percent: -0.78,
    pe_ratio: 42.8,
  },
  {
    id: "fin-007",
    company_name: "Ambuja Cements",
    ticker: "AMBUJACEM",
    market_cap_inr: 1420000,
    market_cap_usd: 17006,
    debt_to_equity: 0.42,
    stock_price: 568.9,
    stock_price_usd: 6.81,
    volume: 5420000,
    sector: "Cement",
    change_percent: 0.54,
    pe_ratio: 48.2,
  },
  {
    id: "fin-008",
    company_name: "ACC Ltd",
    ticker: "ACC",
    market_cap_inr: 620000,
    market_cap_usd: 7425,
    debt_to_equity: 0.28,
    stock_price: 2485.2,
    stock_price_usd: 29.76,
    volume: 1240000,
    sector: "Cement",
    change_percent: 0.92,
    pe_ratio: 52.1,
  },
  {
    id: "fin-009",
    company_name: "NDTV",
    ticker: "NDTV",
    market_cap_inr: 95000,
    market_cap_usd: 1138,
    debt_to_equity: 0.15,
    stock_price: 382.45,
    stock_price_usd: 4.58,
    volume: 856000,
    sector: "Media",
    change_percent: -1.35,
    pe_ratio: 285.4,
  },
  {
    id: "fin-010",
    company_name: "Adani Energy Solutions",
    ticker: "ADANIENSOL",
    market_cap_inr: 980000,
    market_cap_usd: 11737,
    debt_to_equity: 1.65,
    stock_price: 1124.6,
    stock_price_usd: 13.47,
    volume: 3150000,
    sector: "Power Transmission",
    change_percent: 0.68,
    pe_ratio: 65.3,
  },
];

export const newsArticles: NewsArticle[] = [
  {
    id: "news-001",
    title: "Adani Ports Wins Vizhinjam International Terminal Concession",
    source: "Reuters",
    source_tier: 1,
    published_at: "2 hours ago",
    content_snippet:
      "Adani Ports has been awarded the Vizhinjam International Transhipment Terminal concession, marking a significant expansion.",
    validation_score: 0.92,
    bias_risk_level: "Low",
    tag: "Verified",
    related_companies: ["Adani Ports & SEZ"],
    keywords: ["ports", "concession", "infrastructure"],
  },
  {
    id: "news-002",
    title: "Adani Green Energy Announces 10 GW Solar Project in Rajasthan",
    source: "Bloomberg",
    source_tier: 1,
    published_at: "5 hours ago",
    content_snippet:
      "Adani Green Energy announced plans for a 10 GW solar project in Rajasthan, aligning with 45 GW target by 2030.",
    validation_score: 0.88,
    bias_risk_level: "Low",
    tag: "Verified",
    related_companies: ["Adani Green Energy"],
    keywords: ["solar", "renewable"],
  },
  {
    id: "news-003",
    title: "SEBI Tightens Disclosure Norms for Conglomerates",
    source: "The Hindu",
    source_tier: 2,
    published_at: "8 hours ago",
    content_snippet:
      "SEBI has proposed enhanced disclosure requirements for business groups with more than five listed entities.",
    validation_score: 0.78,
    bias_risk_level: "Low",
    tag: "Verified",
    related_companies: ["Adani Enterprises"],
    keywords: ["SEBI", "regulation"],
  },
  {
    id: "news-004",
    title:
      "Adani Group Set to Revolutionize Indian Aviation with New Airport Bids",
    source: "NDTV",
    source_tier: 3,
    published_at: "3 hours ago",
    content_snippet:
      "The Adani Group is reportedly preparing bids for three new airport concessions.",
    validation_score: 0.32,
    bias_risk_level: "High",
    tag: "Requires Verification",
    related_companies: ["Adani Enterprises"],
    keywords: ["airport", "privatization"],
  },
  {
    id: "news-005",
    title: "Adani Total Gas Expands CNG Network to 50 New Districts",
    source: "AP News",
    source_tier: 1,
    published_at: "12 hours ago",
    content_snippet:
      "Adani Total Gas has expanded its CNG distribution network to 50 new districts.",
    validation_score: 0.85,
    bias_risk_level: "Low",
    tag: "Verified",
    related_companies: ["Adani Total Gas"],
    keywords: ["CNG", "expansion"],
  },
  {
    id: "news-006",
    title:
      "Hindenburg Research Publishes Follow-Up on Adani Group Debt Structure",
    source: "OCCRP",
    source_tier: 1,
    published_at: "24 hours ago",
    content_snippet:
      "OCCRP findings examining Adani Group's offshore debt structures raise governance questions.",
    validation_score: 0.91,
    bias_risk_level: "Low",
    tag: "Verified",
    related_companies: ["Adani Group"],
    keywords: ["Hindenburg", "debt"],
  },
  {
    id: "news-007",
    title: "Adani Group Unveils Green Hydrogen Roadmap at RE-Invest 2026",
    source: "Times Now",
    source_tier: 3,
    published_at: "6 hours ago",
    content_snippet:
      "Gautam Adani announced green hydrogen production roadmap targeting 1M tonnes by 2030.",
    validation_score: 0.28,
    bias_risk_level: "High",
    tag: "Requires Verification",
    related_companies: ["Adani Green Energy"],
    keywords: ["green hydrogen"],
  },
  {
    id: "news-008",
    title:
      "India Union Budget 2026-27 Allocates Record Infrastructure Spending",
    source: "BBC",
    source_tier: 1,
    published_at: "48 hours ago",
    content_snippet:
      "Record infrastructure allocation of INR 15 lakh crore in Union Budget 2026-27.",
    validation_score: 0.95,
    bias_risk_level: "Low",
    tag: "Verified",
    related_companies: ["Adani Ports & SEZ"],
    keywords: ["budget", "infrastructure"],
  },
  {
    id: "news-009",
    title: "Adani Defense Wins UAV Supply Contract from Indian Army",
    source: "Business Standard",
    source_tier: 2,
    published_at: "16 hours ago",
    content_snippet:
      "Adani Defense has secured a UAV supply contract under Make in India.",
    validation_score: 0.75,
    bias_risk_level: "Medium",
    tag: "Unverified",
    related_companies: ["Adani Enterprises"],
    keywords: ["defense", "UAV"],
  },
  {
    id: "news-010",
    title: "Adani Data Centers Plans 1 GW Capacity Expansion",
    source: "Financial Times",
    source_tier: 1,
    published_at: "20 hours ago",
    content_snippet:
      "Adani Data Centers planning 1 GW expansion across six Indian cities.",
    validation_score: 0.87,
    bias_risk_level: "Low",
    tag: "Verified",
    related_companies: ["Adani Enterprises"],
    keywords: ["data center", "AI"],
  },
  {
    id: "news-011",
    title: "Electoral Bond Data Reveals Corporate Donation Patterns",
    source: "Scroll.in",
    source_tier: 2,
    published_at: "72 hours ago",
    content_snippet:
      "Analysis of electoral bond data shows significant corporate donations.",
    validation_score: 0.72,
    bias_risk_level: "Medium",
    tag: "Verified",
    related_companies: ["Adani Group"],
    keywords: ["electoral bonds"],
  },
  {
    id: "news-012",
    title: "Adani Wilmar Reports Strong Q4 FY26 Results",
    source: "Reuters",
    source_tier: 1,
    published_at: "10 hours ago",
    content_snippet:
      "Adani Wilmar reported 34% increase in net profit for Q4 FY26.",
    validation_score: 0.9,
    bias_risk_level: "Low",
    tag: "Verified",
    related_companies: ["Adani Wilmar"],
    keywords: ["results", "FMCG"],
  },
  {
    id: "news-013",
    title: "Adani Power Commissions 1600 MW Supercritical Plant",
    source: "The Hindu",
    source_tier: 2,
    published_at: "14 hours ago",
    content_snippet:
      "Adani Power commissions supercritical thermal plant in Jharkhand.",
    validation_score: 0.8,
    bias_risk_level: "Low",
    tag: "Verified",
    related_companies: ["Adani Power"],
    keywords: ["power", "thermal"],
  },
  {
    id: "news-014",
    title: "Adani Group Denies Wrongdoing After SEBI Show Cause Notice",
    source: "Republic TV",
    source_tier: 3,
    published_at: "4 hours ago",
    content_snippet:
      "Adani Group has strongly denied any wrongdoing following SEBI show cause notice.",
    validation_score: 0.22,
    bias_risk_level: "High",
    tag: "Pro-Group",
    related_companies: ["Adani Group"],
    keywords: ["SEBI", "denial"],
  },
  {
    id: "news-015",
    title: "Ambuja Cements Reaches 100 MTPA Milestone",
    source: "Al Jazeera",
    source_tier: 1,
    published_at: "30 hours ago",
    content_snippet:
      "Ambuja Cements reaches 100 MTPA production capacity ahead of schedule.",
    validation_score: 0.89,
    bias_risk_level: "Low",
    tag: "Verified",
    related_companies: ["Ambuja Cements"],
    keywords: ["cement", "milestone"],
  },
];

export const lobbyingRecords: LobbyingRecord[] = [
  {
    id: "lob-001",
    entity: "Adani Group US Operations",
    country: "USA",
    amount_usd: 850000,
    quarter: "Q1",
    year: 2026,
    law_firm: "Brownstein Hyatt Farber Schreck",
    disclosure_type: "Lobbying - Federal",
    description: "Trade policy, energy regulation, India-US bilateral relations",
  },
  {
    id: "lob-002",
    entity: "Adani Ports (US subsidiary)",
    country: "USA",
    amount_usd: 420000,
    quarter: "Q4",
    year: 2025,
    law_firm: "Akin Gump Strauss Hauer & Feld",
    disclosure_type: "Lobbying - Federal",
    description: "Maritime security, port infrastructure funding",
  },
  {
    id: "lob-003",
    entity: "Adani Green Energy (US)",
    country: "USA",
    amount_usd: 310000,
    quarter: "Q3",
    year: 2025,
    law_firm: "Squire Patton Boggs",
    disclosure_type: "Lobbying - Federal",
    description: "IRA implementation, solar tax credits",
  },
  {
    id: "lob-004",
    entity: "Adani Group (via subsidiaries)",
    country: "India",
    amount_usd: 14970060,
    quarter: "Q1",
    year: 2024,
    law_firm: "—",
    disclosure_type: "Electoral Bond",
    description: "Electoral bond purchases Q1 2024",
  },
  {
    id: "lob-005",
    entity: "Adani Group (via subsidiaries)",
    country: "India",
    amount_usd: 10479042,
    quarter: "Q3",
    year: 2023,
    law_firm: "—",
    disclosure_type: "Electoral Bond",
    description: "Electoral bond purchases Q3 2023",
  },
  {
    id: "lob-006",
    entity: "Adani Group (via subsidiaries)",
    country: "India",
    amount_usd: 25149701,
    quarter: "Q4",
    year: 2022,
    law_firm: "—",
    disclosure_type: "Electoral Bond",
    description: "Electoral bond purchases Q4 2022 (largest)",
  },
  {
    id: "lob-007",
    entity: "Adani Group",
    country: "Australia",
    amount_usd: 450000,
    quarter: "Q2",
    year: 2025,
    law_firm: "Barton Deakin",
    disclosure_type: "Lobbying - State",
    description: "Queensland mining and renewable energy policy",
  },
  {
    id: "lob-008",
    entity: "Adani Group",
    country: "USA",
    amount_usd: 280000,
    quarter: "Q2",
    year: 2025,
    law_firm: "Williams & Jensen",
    disclosure_type: "Lobbying - Federal",
    description: "International trade, India-US energy cooperation",
  },
  {
    id: "lob-009",
    entity: "Adani Group",
    country: "Tanzania",
    amount_usd: 180000,
    quarter: "Q1",
    year: 2025,
    law_firm: "Local Counsel",
    disclosure_type: "Consultancy",
    description: "Port development project, East Africa",
  },
  {
    id: "lob-010",
    entity: "Adani Ports",
    country: "Israel",
    amount_usd: 320000,
    quarter: "Q3",
    year: 2024,
    law_firm: "Government Relations Counsel",
    disclosure_type: "Lobbying - Foreign",
    description: "Haifa Port operations, trade facilitation",
  },
];

export const acquisitions: Acquisition[] = [
  {
    id: "acq-001",
    company_acquired: "ACC Ltd (Majority Stake)",
    acquirer: "Adani Group (via Ambuja)",
    year: 2022,
    valuation_inr: 51000,
    valuation_usd: 611,
    status: "Integrated",
    sector: "Cement",
  },
  {
    id: "acq-002",
    company_acquired: "Ambuja Cements",
    acquirer: "Adani Group",
    year: 2022,
    valuation_inr: 31000,
    valuation_usd: 371,
    status: "Active",
    sector: "Cement",
  },
  {
    id: "acq-003",
    company_acquired: "NDTV",
    acquirer: "AMG Media Networks",
    year: 2022,
    valuation_inr: 1140,
    valuation_usd: 14,
    status: "Active",
    sector: "Media",
  },
  {
    id: "acq-004",
    company_acquired: "Jaypee Infratech",
    acquirer: "Adani Properties",
    year: 2023,
    valuation_inr: 25000,
    valuation_usd: 299,
    status: "Pending Litigation",
    sector: "Real Estate",
  },
  {
    id: "acq-005",
    company_acquired: "DB Power Ltd",
    acquirer: "Adani Power",
    year: 2023,
    valuation_inr: 70200,
    valuation_usd: 841,
    status: "Integrated",
    sector: "Power",
  },
  {
    id: "acq-006",
    company_acquired: "Warora-Hingoni MW Power",
    acquirer: "Adani Power",
    year: 2024,
    valuation_inr: 48000,
    valuation_usd: 575,
    status: "Active",
    sector: "Power",
  },
  {
    id: "acq-007",
    company_acquired: "ITD Cementation India",
    acquirer: "Adani Group",
    year: 2024,
    valuation_inr: 55000,
    valuation_usd: 659,
    status: "Active",
    sector: "Infrastructure / EPC",
  },
  {
    id: "acq-008",
    company_acquired: "Haigreeva Inc (Biofuels)",
    acquirer: "Adani Total Gas",
    year: 2025,
    valuation_inr: 35000,
    valuation_usd: 419,
    status: "Active",
    sector: "Green Energy",
  },
  {
    id: "acq-009",
    company_acquired: "Trade Castle (Logistics Tech)",
    acquirer: "Adani Ports & SEZ",
    year: 2024,
    valuation_inr: 12000,
    valuation_usd: 144,
    status: "Integrated",
    sector: "Logistics / Tech",
  },
  {
    id: "acq-010",
    company_acquired: "JP Associates (Cement Assets)",
    acquirer: "Ambuja Cements",
    year: 2025,
    valuation_inr: 65000,
    valuation_usd: 778,
    status: "Active",
    sector: "Cement",
  },
  {
    id: "acq-011",
    company_acquired: "Mumbai Airport (CSMIA)",
    acquirer: "Adani Airports",
    year: 2021,
    valuation_inr: 0,
    valuation_usd: 0,
    status: "Active",
    sector: "Aviation",
  },
  {
    id: "acq-012",
    company_acquired: "6 AAI Airports (Concession)",
    acquirer: "Adani Airports",
    year: 2020,
    valuation_inr: 0,
    valuation_usd: 0,
    status: "Active",
    sector: "Aviation",
  },
  {
    id: "acq-013",
    company_acquired: "Dighi Port Ltd",
    acquirer: "Adani Ports & SEZ",
    year: 2021,
    valuation_inr: 850,
    valuation_usd: 10,
    status: "Integrated",
    sector: "Ports",
  },
  {
    id: "acq-014",
    company_acquired: "Karaikal Port",
    acquirer: "Adani Ports & SEZ",
    year: 2023,
    valuation_inr: 1485,
    valuation_usd: 18,
    status: "Active",
    sector: "Ports",
  },
  {
    id: "acq-015",
    company_acquired: "NDTV (Additional Stake)",
    acquirer: "AMG Media Networks",
    year: 2023,
    valuation_inr: 0,
    valuation_usd: 0,
    status: "Active",
    sector: "Media",
  },
  {
    id: "acq-016",
    company_acquired: "Sarguja Rail Corridor",
    acquirer: "Adani Power",
    year: 2023,
    valuation_inr: 22000,
    valuation_usd: 263,
    status: "Active",
    sector: "Rail Infrastructure",
  },
  {
    id: "acq-017",
    company_acquired: "MyHome Industries (Cement)",
    acquirer: "Ambuja Cements",
    year: 2025,
    valuation_inr: 18000,
    valuation_usd: 216,
    status: "Active",
    sector: "Cement",
  },
  {
    id: "acq-018",
    company_acquired: "Symbiottic Software (AI)",
    acquirer: "Adani Data Networks",
    year: 2025,
    valuation_inr: 320,
    valuation_usd: 4,
    status: "Integrated",
    sector: "Digital / Technology",
  },
  {
    id: "acq-019",
    company_acquired: "Carmichael Coal Mine",
    acquirer: "Bravus Mining (Adani)",
    year: 2019,
    valuation_inr: 0,
    valuation_usd: 0,
    status: "Demerged",
    sector: "Mining",
  },
  {
    id: "acq-020",
    company_acquired: "Urja Global (Stake)",
    acquirer: "Adani Green Energy",
    year: 2024,
    valuation_inr: 8200,
    valuation_usd: 98,
    status: "Active",
    sector: "Renewable Energy",
  },
];
